[namespace]
default = "eternum"

[env]
account_address = "0x40f749bc315c75f3dc575490955b3595c736378054cc8ee80379e811f36fc7d"
private_key = "0x1c2304d35a10f6199004c2e4ef913194ac86622852388db7f3ce2a6816cfa90"
rpc_url = "https://api.cartridge.gg/x/eternum-45/katana"

[world]
seed = "eternum"
name = "Realms: Eternum"
description = "Rule the Hex"
cover_uri = "file://assets/bg.webp"
website = "https://eternum.realms.world/"
