[namespace]
default = "eternum"

[env]
account_address = "0x7fffe1c02b36039bb5d0134c8a9f0fb7927d64509ad6fb59860c6e9dadf91f9"
private_key = "0x1359b06cc87b7de694e700e944b38abeffbb8032f61aee22575d96602a086b9"
rpc_url = "https://api.cartridge.gg/x/eternum-rc1/katana"

[world]
seed = "eternum"
name = "Realms: Eternum"
description = "Rule the Hex"
cover_uri = "file://assets/bg.webp"
website = "https://eternum.realms.world/"

[writers]
"eternum" = [
    "eternum-bank_systems",
    "eternum-battle_pillage_systems",
    "eternum-battle_systems",
    "eternum-building_systems",
    "eternum-config_systems",
    "eternum-dev_bank_systems",
    "eternum-dev_realm_systems",
    "eternum-dev_resource_systems",
    "eternum-donkey_systems",
    "eternum-guild_systems",
    "eternum-hyperstructure_systems",
    "eternum-liquidity_systems",
    "eternum-map_systems",
    "eternum-name_systems",
    "eternum-ownership_systems",
    "eternum-realm_systems",
    "eternum-resource_bridge_systems",
    "eternum-resource_systems",
    "eternum-swap_systems",
    "eternum-trade_systems",
    "eternum-travel_systems",
    "eternum-troop_systems",
]
