[namespace]
default = "eternum"

[env]
account_address = "0x24c2cabac53965693c322c98061ea40469ca0ce640408fd69c960ef61d6d950"
private_key = "0x7ca06a1fbb9ae7c672a345c647942c632ffe42ee730897131b5335b5fbfb460"
rpc_url = "https://api.cartridge.gg/x/eternum-44/katana"

[world]
seed = "eternum"
name = "Realms: Eternum"
description = "Rule the Hex"
cover_uri = "file://assets/bg.webp"
website = "https://eternum.realms.world/"
