db_dir = "./torii.db"

[indexing]
events_chunk_size = 1024 # Size of events page to fetch
blocks_chunk_size = 10240 # Blocks to process before DB commit
index_pending = true # Enable indexing pending blocks
polling_interval = 500 # Polling interval in milliseconds
max_concurrent_tasks = 100 # Maximum concurrent indexing tasks
index_transactions = true
contracts = [
  "erc721:0x75dadf278a8618fb51a69bb7d3aafac4c512f3507df9ad485856d79ca205a33",
  "erc721:0x10cbb589b71c2633929eaa3207c942fea498d6834281424e3e2ec28bf59f99f",
]
