name: knip

on:
  push:
    paths:
      - "client/**"
    branches: [main]
  pull_request: 
    paths:
      - "client/**"


jobs:
  knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm i

      - name: Run knip
        run: pnpm knip
